/**
 * REMANENCE: What remains.
 * Storytelling about NASA's Discarded Equipment on the Moon and Mars
 * Complete mission data, timeline telemetry, and historical facts.
 * Verified against NASA archives, NSSDC, and JPL mission logs.
 * English language only.
 */

export const STORY_DATA = {
  meta: {
    title: "REMANENCE",
    tagline: "What remains.",
    definition: "remanence (n.) — what remains after the force is gone."
  },

  sections: [
    {
      id: "intro",
      type: "intro",
      title: "REMANENCE",
      tagline: "What remains.",
      lead: "Translunar Insertion · 1969 to Present",
      instruction: "Scroll to explore"
    },

    {
      id: "earth",
      type: "overview",
      chapter: "Chapter 00 · Origin",
      title: "Planet Earth",
      machineTitle: "Launch Site Earth",
      location: "Cape Canaveral, Florida · 28.57° N, 80.65° W",
      date: "1969 to Present",
      status: "Active Origin",
      summary: "Every footprint on other worlds and every signal echoing through the deep void began from this fragile blue marble.",
      story: "From this fragile blue marble against the dark, humanity dared to cast metal, glass, and collective memory into the vacuum. We sent our mechanical emissaries across the void to see what human eyes could not yet reach.",
      coordinates: "28.5721° N, 80.6480° W",
      sourceLabel: "NASA Earth Observatory",
      sourceUrl: "https://earthobservatory.nasa.gov/"
    },

    {
      id: "apollo11",
      type: "machine",
      chapter: "Chapter 01 · Apollo 11",
      title: "Apollo 11 Descent Stage",
      machineTitle: "Lunar Module LM-5 'Eagle'",
      location: "Mare Tranquillitatis · 0.674° N, 23.473° E",
      lastContact: "July 24, 1969 (Descent Stage Shutdown: July 21, 1969)",
      status: "Silent",
      summary: "Neil Armstrong and Buzz Aldrin brought Eagle down with seconds of fuel remaining; when the ascent engine fired, the descent stage remained forever.",
      remanence: "Gold Kapton foil, stainless steel plaque, and pristine astronaut bootprints in vacuum.",
      story: "Neil Armstrong and Buzz Aldrin brought Eagle down with seconds of fuel remaining. When the ascent engine fired to bring them home, the descent stage remained. Bolted to its forward strut is a plaque: 'Here men from the planet Earth first set foot upon the Moon. We came in peace for all mankind.' In the airless lunar silence, its gold Kapton foil glints in unfiltered sunlight.",
      coordinates: "0.67408° N, 23.47297° E",
      modelType: "apollo_lm",
      glowColor: 0xffb84d,
      lightIntensity: 1.8,
      fact: "The descent stage carries a silicon goodwill disc etched with messages from 73 world leaders and four US presidents.",
      sourceLabel: "Apollo Lunar Surface Journal (ALSJ)",
      sourceUrl: "https://www.nasa.gov/history/alsj/a11/a11.html"
    },

    {
      id: "alsep",
      type: "machine",
      chapter: "Chapter 02 · ALSEP Station",
      title: "Apollo Science Stations",
      machineTitle: "Apollo Lunar Surface Experiments Package",
      location: "Apollo 12, 14, 15, 16, 17 Landing Sites",
      lastContact: "September 30, 1977 (Commanded Off by NASA)",
      status: "Decommissioned in Place",
      summary: "Powered by nuclear SNAP-27 thermoelectric generators, the ALSEP stations continuously beamed moonquake and solar wind data to Earth for eight straight years until commanded off on September 30, 1977.",
      remanence: "Central stations, plutonium-238 casks, and seismometer packages resting across five lunar plains.",
      story: "Each Apollo landing crew from Apollo 12 through 17 hand-deployed an automated scientific laboratory powered by a SNAP-27 radioisotope thermoelectric generator. For up to eight continuous years, these stations monitored moonquakes, recorded meteorite strikes, and mapped the solar wind. On September 30, 1977, NASA sent the final command terminating telemetry transmission due to operational cost constraints. The hardware stands intact and silent across five landing plains.",
      coordinates: "Apollo 12 (3.01° S), Apollo 14 (3.64° S), Apollo 15 (26.13° N), Apollo 16 (8.97° S), Apollo 17 (20.19° N)",
      modelType: "alsep",
      glowColor: 0xffb84d,
      lightIntensity: 1.7,
      fact: "The ALSEP seismometers recorded over 12,000 moonquakes and confirmed the Moon has a small partially molten metallic core.",
      sourceLabel: "NASA NSSDC ALSEP Archive",
      sourceUrl: "https://nssdc.gsfc.nasa.gov/lunar/alsep.html"
    },

    {
      id: "lrv",
      type: "machine",
      chapter: "Chapter 03 · Lunar Rovers",
      title: "Lunar Roving Vehicles",
      machineTitle: "LRV-1, LRV-2, LRV-3",
      location: "Hadley Rille, Descartes Highlands & Taurus-Littrow (Apollo 15, 16, 17)",
      lastContact: "December 14, 1972 (Apollo 17 Departure)",
      status: "Silent",
      summary: "Three electric buggies expanded exploration across ancient lunar valleys, parked facing the stars after broadcasting the final crewed ascent liftoffs.",
      remanence: "Three electric buggies parked toward the stars; tire tracks crisp in the regolith.",
      story: "Between 1971 and 1972, three electric buggies carried astronauts across ancient lunar mountains and rilles. Commander Eugene Cernan parked LRV-3 a hundred meters away at the 'VIP site' so ground controllers in Houston could operate its color TV camera and broadcast the final crewed ascent ignition. No human hand has touched its steering control in over fifty years; its zinc-silver batteries have long gone cold beneath the stars.",
      coordinates: "20.1908° N, 30.7717° E (Apollo 17 Site)",
      modelType: "lrv_rover",
      glowColor: 0xffb84d,
      lightIntensity: 1.6,
      fact: "During Apollo 17, Gene Cernan and Harrison Schmitt repaired a broken rear fender with taped lunar maps to stop rooster tails of abrasive regolith.",
      sourceLabel: "Apollo Lunar Surface Journal LRV Operations",
      sourceUrl: "https://www.nasa.gov/history/alsj/alsj-LRV.html"
    },

    {
      id: "hammer_feather",
      type: "machine",
      chapter: "Chapter 04 · The Galileo Test",
      title: "The Hammer and the Feather",
      machineTitle: "Apollo 15 Experimental Site",
      location: "Hadley Rille, Moon · 26.13° N, 3.63° E",
      lastContact: "August 2, 1971 (Demonstration by David Scott)",
      status: "Preserved in Vacuum",
      summary: "Commander David Scott dropped an aluminum geology hammer and a falcon feather simultaneously in the lunar vacuum, proving Galileo's law of gravity; both artifacts remain undisturbed on the lunar dust.",
      remanence: "A 1.3-kg aluminum geology hammer and a white falcon feather resting side by side in the dust.",
      story: "Standing before the lunar television camera at the foot of Mount Hadley Delta, Commander David Scott released an aluminum geological hammer and a white falcon feather simultaneously. In the lunar vacuum, with no atmospheric drag, both fell at the exact same rate and struck the dust together—confirming Galileo Galilei's 17th-century deduction. Scott noted: 'How about that? Mr. Galileo was correct in his findings.' The hammer and feather remain exactly where they dropped.",
      coordinates: "26.1322° N, 3.6339° E",
      modelType: "hammer_feather",
      glowColor: 0xffb84d,
      lightIntensity: 1.5,
      fact: "The feather was taken from 'Baggin', the female mascot gyrfalcon of the United States Air Force Academy.",
      sourceLabel: "NASA Apollo 15 Flight Journal",
      sourceUrl: "https://www.nasa.gov/history/alsj/a15/a15.hammerdrop.html"
    },

    {
      id: "surveyor3",
      type: "machine",
      chapter: "Chapter 05 · Surveyor 3",
      title: "Surveyor 3 Revisited",
      machineTitle: "Surveyor 3 Lunar Lander",
      location: "Oceanus Procellarum · 3.015° S, 23.418° W",
      lastContact: "May 4, 1967 (Inspected by Apollo 12: Nov 19, 1969)",
      status: "Silent",
      summary: "Two years after Surveyor 3 bounced to rest inside a crater, Apollo 12 astronauts pinpoint-landed nearby to examine the hardware and retrieve its camera for return to Earth.",
      remanence: "Weathered tubular aluminum tripod standing inside Surveyor Crater.",
      story: "Two years after Surveyor 3 bounced to rest inside a gentle crater, Apollo 12 astronauts Pete Conrad and Alan Bean pinpoint-landed within walking distance. They walked down the crater slope to inspect the machine and removed its television camera, polarimetric filter, and sampling scoop to bring back to Earth for analysis. It remains the only time in human history that astronauts visited a robotic probe previously sent to another world.",
      coordinates: "3.015° S, 23.418° W",
      modelType: "surveyor",
      glowColor: 0xc9ccd6,
      lightIntensity: 1.5,
      fact: "Analysis of the returned camera revealed micro-cratering from micrometeorites and sandblasting caused by Apollo 12's descent engine exhaust.",
      sourceLabel: "LPI Surveyor 3 Analysis",
      sourceUrl: "https://www.lpi.usra.edu/lunar/missions/apollo/apollo_12/experiments/surveyor3/"
    },

    {
      id: "transit",
      type: "transit",
      chapter: "Chapter 06 · The Crossing",
      title: "The Crossing",
      machineTitle: "Interplanetary Space",
      location: "Translunar to Trans-Mars Trajectory",
      date: "225 Million Kilometers",
      status: "Crossing Void",
      summary: "Between the silver dust of the Moon and the rusted sands of Mars lies months of profound silence, punctuated only by radio signals traveling at the speed of light.",
      remanence: "225 million kilometers of cosmic radiation and silent heliocentric orbits.",
      story: "Leaving the Moon behind, the journey stretches into the vast chasm between planetary orbits. Space is not empty; it is filled with solar wind, cosmic radiation, and the fading echoes of radio transmissions traveling at the speed of light. Out here, human voices thin into faint telemetry pings echoing across the dark.",
      coordinates: "Heliocentric Orbit (1.52 AU)",
      sourceLabel: "NASA JPL Solar System Dynamics",
      sourceUrl: "https://ssd.jpl.nasa.gov/"
    },

    {
      id: "descent_debris",
      type: "machine",
      chapter: "Chapter 07 · Descent Debris",
      title: "Mars Descent Debris",
      machineTitle: "Entry, Descent & Landing Hardware",
      location: "Jezero Crater, Gale Crater & Chryse Planitia",
      lastContact: "Touchdown Epochs: 1976 to 2021",
      status: "Scattered Artifacts",
      summary: "To land safely on Mars, missions must discard their protective shields: supersonic parachutes, conical backshells, and sky-crane descent stages lie scattered across the red dunes.",
      remanence: "Conical backshells, orange-and-white supersonic parachutes, and charred sky-crane impact scars.",
      story: "Surviving entry into the Martian atmosphere requires shedding hardware at hypervelocity. Miles away from where rovers roll, their orange-and-white supersonic parachutes billow on the sand, backshells sit crushed from free-fall impact, and sky cranes leave charred scars where they deliberately crash-landed after winching their payloads to safety. In 2022, Ingenuity flew over Perseverance's backshell and parachute, photographing the wreckage from the air.",
      coordinates: "18.38° N, 77.58° E (Perseverance EDL Site)",
      modelType: "descent_debris",
      glowColor: 0xe8643c,
      lightIntensity: 1.7,
      fact: "Perseverance's supersonic parachute contained a hidden binary code in its orange-and-white gores: 'Dare Mighty Things'.",
      sourceLabel: "NASA JPL Mars EDL Technology",
      sourceUrl: "https://mars.nasa.gov/mars2020/mission/technology/entry-descent-landing/"
    },

    {
      id: "viking1",
      type: "machine",
      chapter: "Chapter 08 · Viking 1",
      title: "Viking 1 Lander",
      machineTitle: "Thomas Mutch Memorial Station",
      location: "Chryse Planitia · 22.697° N, 48.222° W",
      lastContact: "November 11, 1982 (2,245 Sols of Operation)",
      status: "Silent",
      summary: "On the seventh anniversary of Apollo 11, Viking 1 touched the red soil of Chryse Planitia and transmitted humanity's first clear color photograph from the surface of Mars.",
      remanence: "Titanium lander body, meteorology boom, and trench scoops preserved in red dust.",
      story: "On July 20, 1976—seven years to the day after Apollo 11—Viking 1 touched the red soil of Chryse Planitia and transmitted humanity's first clear view from the surface of Mars: amber skies and red boulders. For over six Earth years (2,245 sols), it measured weather, soil chemistry, and daily seismology until a ground software upload accidentally overwrote its antenna pointing coordinates. Its robotic arm remains poised forever over the soil trench it dug.",
      coordinates: "22.697° N, 48.222° W",
      modelType: "viking_lander",
      glowColor: 0xe8643c,
      lightIntensity: 1.8,
      fact: "Viking 1 operated on Mars for over six Earth years, far exceeding its original 90-day design lifetime.",
      sourceLabel: "NASA PDS Viking Lander Archive",
      sourceUrl: "https://pds-imaging.jpl.nasa.gov/volumes/viking.html"
    },

    {
      id: "pathfinder",
      type: "machine",
      chapter: "Chapter 09 · Pathfinder",
      title: "Pathfinder & Sojourner",
      machineTitle: "Carl Sagan Memorial Station",
      location: "Ares Vallis · 19.33° N, 33.55° W",
      lastContact: "September 27, 1997 (Sol 83)",
      status: "Silent",
      summary: "Bouncing onto Mars inside giant airbags on July 4, 1997, Pathfinder opened its petals to release Sojourner—humanity's first mobile rover on another world.",
      remanence: "The Carl Sagan Memorial Station petals and the 10.5-kg six-wheeled rover parked nearby.",
      story: "Pathfinder bounced onto Mars cushioned inside airbags on July 4, 1997, unfurling three solar petals to release Sojourner—the first wheeled rover to drive on another planet. The 10.5-kg microrover sniffed Martian rocks named 'Barnacle Bill' and 'Yogi'. Outliving its 7-day design life for 83 sols, it analyzed soil and rocks until the lander's primary battery expired in the autumn cold. Both lander and rover remain preserved across the ancient Ares Vallis floodplain.",
      coordinates: "19.33° N, 33.55° W",
      modelType: "pathfinder_sojourner",
      glowColor: 0xe8643c,
      lightIntensity: 1.6,
      fact: "Sojourner was named in honor of abolitionist and orator Sojourner Truth.",
      sourceLabel: "NASA JPL Mars Pathfinder Archive",
      sourceUrl: "https://mars.nasa.gov/mars-pathfinder/mission/sojourner.html"
    },

    {
      id: "spirit",
      type: "machine",
      chapter: "Chapter 10 · Spirit",
      title: "Spirit Rover (MER-A)",
      machineTitle: "Mars Exploration Rover 'Spirit'",
      location: "Gusev Crater · 14.568° S, 175.473° E",
      lastContact: "March 22, 2010 (Sol 2210)",
      status: "Silent",
      summary: "Designed for 90 days, Spirit explored Gusev Crater for six years until its wheels broke through crust into fine sulfate sand at 'Troy', greeting its final freezing winter.",
      remanence: "Six aluminum wheels trapped in sulfate sand; solar panels angled toward a cold winter horizon.",
      story: "Designed to drive 600 meters over 90 days, Spirit battled through rocky terrain for more than six years. When its right front wheel jammed, engineers drove the rover backward, dragging the dead wheel across the soil—which inadvertently dug open brilliant deposits of pure silica, proving volcanic hot springs once bubbled on Mars. In May 2009, its wheels broke into powder-fine sulfate sand at 'Troy'. Trapped and unable to angle its solar arrays toward the winter sun, Spirit sent its final transmission on March 22, 2010.",
      coordinates: "14.5684° S, 175.4726° E",
      modelType: "mer_rover",
      glowColor: 0xe8643c,
      lightIntensity: 1.7,
      fact: "Spirit's dragged wheel serendipitously uncovered 90% pure silica, one of the mission's most significant scientific discoveries.",
      sourceLabel: "NASA PDS Mars Exploration Rover Archive",
      sourceUrl: "https://pds-geosciences.wustl.edu/missions/mer/"
    },

    {
      id: "opportunity",
      type: "machine",
      chapter: "Chapter 11 · Opportunity",
      title: "Opportunity in Twilight",
      machineTitle: "MER-B 'Oppy'",
      location: "Endeavour Crater · 2.327° S, 354.673° E",
      lastContact: "June 10, 2018 (Sol 5111)",
      lastData: "tau 10.8 · 22 Wh",
      paraphrase: "Often paraphrased as: “My battery is low and it is getting dark.”",
      status: "Silent",
      summary: "Opportunity traversed an off-world marathon of 45.16 kilometers before a planet-encircling dust storm plunged Endeavour Crater into pitch darkness.",
      remanence: "A marathon path of 45.16 kilometers etched into red sand; solar arrays blanketed in dust.",
      story: "For nearly fifteen years, Opportunity traversed the Meridiani plains, discovering hematite 'blueberries' formed in ancient water. In June 2018, a catastrophic planet-wide dust storm blotted out 99% of sunlight. Its final telemetry recorded an atmospheric opacity tau of 10.8 and array power dropping to 22 watt-hours, famously paraphrased as: 'My battery is low and it is getting dark.' Over eight months, NASA transmitted more than a thousand recovery commands into the silence. None were answered.",
      coordinates: "2.327° S, 354.673° E",
      modelType: "mer_rover_oppy",
      glowColor: 0xffb84d,
      lightIntensity: 2.0,
      dustStorm: true,
      fact: "Opportunity holds the all-time off-world driving record: 45.16 km (28.06 miles), surpassing Apollo 17's LRV distance.",
      sourceLabel: "NASA JPL Opportunity Mission Status",
      sourceUrl: "https://mars.nasa.gov/mer/mission/status/opportunity/all/2018/"
    },

    {
      id: "ingenuity",
      type: "machine",
      chapter: "Chapter 12 · Ingenuity",
      title: "Ingenuity Rotorcraft",
      machineTitle: "Mars Helicopter 'Ginny'",
      location: "Valinor Hills, Jezero Crater · 18.445° N, 77.451° E",
      lastContact: "January 18, 2024 (Mission Concluded: Jan 25, 2024)",
      status: "Retired Honorably",
      remanence: "Severed rotor blade tips resting on the sand ripples of Valinor Hills.",
      summary: "Carrying a swatch of fabric from the Wright Brothers' 1903 Flyer, Ingenuity proved powered flight on Mars across 72 missions before rotor tip damage on Flight 72 concluded its journey.",
      story: "Carrying a postage-stamp swatch of muslin from the Wright Brothers' 1903 Flyer, Ingenuity proved powered atmospheric flight is possible in Mars' razor-thin atmosphere. Originally planned for five experimental test hops, the 1.8-kg drone completed 72 flights across Jezero Crater. On its final landing in January 2024, rotor blade tip damage ended its flights. The helicopter remains grounded on the sand ripples of Valinor Hills, having permanently proven aerial exploration on other worlds.",
      coordinates: "18.445° N, 77.451° E",
      modelType: "ingenuity",
      glowColor: 0xe8643c,
      lightIntensity: 1.9,
      fact: "Ingenuity clocked 128.8 total flight minutes across 17 kilometers, soaring as high as 24 meters above the Martian surface.",
      sourceLabel: "NASA JPL Ingenuity Status",
      sourceUrl: "https://mars.nasa.gov/technology/helicopter/status/"
    },

    {
      id: "retroreflector",
      type: "finale",
      chapter: "Chapter 13 · The Answering Signal",
      title: "The Answering Signal",
      machineTitle: "Lunar Laser Ranging Retroreflectors (LRRR)",
      location: "Apollo 11, 14, 15 Landing Sites, Moon",
      lastContact: "Pulsed Today (Round-trip time: ~2.56 seconds)",
      status: "Perpetually Active",
      summary: "Fifty years after Apollo, astronomers at Apache Point, Observatoire de la Côte d'Azur, and Matera still fire green lasers at silent quartz prisms, catching returning photons.",
      remanence: "Solid quartz corner-cube prisms bouncing green photon lasers back to Earth right now.",
      story: "Fifty years after human boots left the regolith, there is one Apollo experiment that has never gone silent. The Lunar Laser Ranging Retroreflectors require no batteries, no solar cells, and no computers. Astronomers at Apache Point Observatory in New Mexico, Observatoire de la Côte d'Azur in France, and Matera Laser Ranging Observatory in Italy still fire high-powered green lasers through telescopes directly at these silent quartz prisms, catching single returning photons to calculate the Moon's distance to millimeter precision.",
      coordinates: "Apollo 11 (23.47° E), Apollo 14 (17.47° W), Apollo 15 (3.63° E)",
      modelType: "retroreflector",
      glowColor: 0x6fe3ff,
      laserActive: true,
      fact: "Laser ranging proved the Moon is spiraling away from Earth at a rate of approximately 3.8 centimeters per year.",
      sourceLabel: "NASA Lunar Laser Ranging Science",
      sourceUrl: "https://science.nasa.gov/moon/laser-ranging/"
    },

    {
      id: "sources",
      type: "archive",
      chapter: "Chapter 14 · Archive & Sources",
      title: "Data & Sources",
      machineTitle: "Scientific Documentation",
      location: "NASA Scientific Archives",
      status: "Verified",
      coordinates: "NASA Scientific Archives",
      story: "Every date, coordinate, and telemetry log in REMANENCE is verified against official NASA historical and mission archives.",
      sourceLabel: "NASA Planetary Data System (PDS)",
      sourceUrl: "https://pds.nasa.gov/"
    }
  ]
};
